/* ==========================================================================
   THE BUNKER — COMMAND OS
   config.js — Constantes de Entorno, Tarifas e Internacionalización (i18n)
   Fase 5/6: Radar en vivo (WebSocket), analítica de comunidad y checkout
   exclusivo con Telegram Stars (XTR).
   ========================================================================== */

export const CONFIG = {
    BOT_USERNAME: 'thebunkerapp_bot',
    WEBAPP_URL: 'https://thebunkerapp2.netlify.app/',
    API_BASE: 'https://the-bunker-bot-production.up.railway.app',

    // 📡 Radar en vivo: el WebSocket del backend vive en el mismo dominio de Railway
    // (ruta /ws/radar/{chat_id}). Debe usar wss:// porque la Mini App se sirve por HTTPS.
    WS_BASE: 'wss://the-bunker-bot-production.up.railway.app',

    // Un único medio de pago: Telegram Stars (XTR). Sin pasarelas externas ni precios fiat.
    PRICES: {
        pro:   { stars: 300 },
        ultra: { stars: 600 }
    },

    // ⚡ Parámetros del cliente WebSocket (BunkerWebSocketClient)
    WS: {
        // 'query' → ?init_data= / ?token= en la URL | 'frame' → primer frame {action:'auth'}
        // (evita que las credenciales aparezcan en los logs de acceso del proxy).
        AUTH_MODE: 'query',
        HEARTBEAT_MS: 20000,        // ping cada 20 s (el servidor corta a los 90 s de silencio)
        PONG_TIMEOUT_MS: 10000,     // sin ningún mensaje tras un ping → conexión muerta
        BACKOFF_BASE_MS: 1000,      // reconexión exponencial: 1 s, 2 s, 4 s ... hasta el tope
        BACKOFF_MAX_MS: 30000,
        BACKOFF_FACTOR: 2,
        RATE_LIMITED_MIN_MS: 30000, // cierre 4429 (sala llena / demasiadas sesiones)
        HIDDEN_PAUSE_MS: 60000      // pausa la conexión si la Mini App lleva 60 s en segundo plano
    },

    // 📈 Analítica de comunidad
    ANALYTICS: {
        REST_TIMEOUT_MS: 12000,
        REFRESH_MIN_MS: 20000,          // mínimo entre refrescos pedidos tras eventos en vivo
        FEED_MAX_ITEMS: 30,
        MESSAGE_TOAST_WINDOW_MS: 2500,  // agrupa los mensajes en vivo en un único aviso
        TOAST_MAX_VISIBLE: 3
    }
};

export const translations = {
    es: {
        plans_title: "Membresías de Comunidad",
        basic_badge: "ACCESO GRATUITO",
        basic_title: "Plan BÁSICO",
        basic_desc: "Comandos de moderación limitados. Sin automatización de radar ni soporte prioritario.",
        btn_free_active: "Activo por defecto",
        pro_badge: "PLAN MENSUAL",
        pro_title: "Plan PRO",
        pro_desc: "Automatización total, moderación de voz y comandos ilimitados para tu comunidad.",
        ultra_badge: "ACCESO ILIMITADO",
        ultra_title: "ULTRA PRO",
        ultra_desc: "Radar avanzado anti-fantasmas, prioridad máxima en servidores y soporte directo.",
        plans_stars_only: "Pago 100% in-app con Telegram Stars (XTR). Activación inmediata.",
        active_context: "Entorno Activo:",
        stat_subs: "Suscriptores VIP",
        stat_revenue: "Ingresos Stars",
        live_sync: "Sincronización en vivo",
        stat_source: "Datos reales del bot",
        dash_telemetry: "Telemetría del Búnker",
        online_tag: "En Línea 🟢",
        stat_verified: "Verificados",
        stat_expelled: "Expulsados",
        stat_purges: "Purgas",
        perimeter_title: "Perímetro Operativo",
        perimeter_sub: "Supervisión 24/7",
        captcha_label: "Aduana Captcha:",
        autolower_label: "Radar AutoLower:",
        shield_label: "Escudo Antinota:",
        broadcast_label: "Difusión Recurrente:",
        linked_channels: "Canales Conectados",
        linked_groups: "Comunidades Conectadas",
        sync: "Sincronizar",
        syncing: "Sincronizando...",
        configure: "Configurar",
        license_active: "Activa 🟢",
        license_renew: "Renovar",
        btn_logout: "Cerrar Sesión",
        no_channels: "Sin canales vinculados aún",
        no_groups: "Sin comunidades vinculadas aún",
        no_subs: "Sin suscriptores registrados",
        aff_title: "Red de Afiliados & Comisiones",
        aff_desc: "Comparte tu enlace único de promotor. Cada vez que una comunidad adquiera un plan PRO o ULTRA a través de tu recomendación, recibes comisiones instantáneas en Telegram Stars directo a tu balance.",
        nav_dash: "Telemetría & Stats",
        nav_channels: "Estudio de Canales",
        nav_groups: "Matriz de Grupos",
        nav_watchdog: "Auditor Suscripciones",
        nav_plans: "Membresías & Stars",
        nav_analytics: "Analítica en Vivo",
        nav_aff: "Red de Afiliados",
        studio_badge: "ESTUDIO DE BROADCAST",
        studio_title: "Ajustes del Canal",
        btn_open_studio: "Guardar Ajustes",
        channel_owner_label: "Canal Bajo tu ID de Creador:",
        vip_delivery_title: "Enlace VIP & Entrega Automática",
        vip_target_label: "Destino VIP (Canal Privado / Recurso):",
        stars_rate_label: "Tarifa en Stars (XTR):",
        duration_days_label: "Duración (Días):",
        perimeter_badge: "PERÍMETRO COMUNITARIO",
        groups_title: "Control de Grupos",
        shielded_mode: "Modo Blindado 🟢",
        group_owner_label: "Comunidad Administrada:",
        captcha_pro: "Aduana Captcha Pro",
        captcha_desc: "Desafío privado antes de ingresar",
        autolower_title: "AutoLower de Micrófonos (2%)",
        autolower_desc: "Atenuación acústica de fondo",
        shield_title: "Escudo Antinota",
        shield_desc: "Corte de pantalla compartida",
        linklock_title: "Cerradura de Enlaces Web",
        linklock_desc: "Purga inmediata de URLs no permitidas",
        watchdog_badge: "MONITOR DE MIEMBROS",
        watchdog_title: "Aviso de Suscripciones",
        live_badge: "En Vivo",
        watchdog_desc: "Supervisa en tiempo real el tiempo restante de cada miembro suscrito y las alertas de renovación antes del Auto-Kick automático.",
        profile_balance_stars: "Balance Stars:",
        profile_discount: "Descuento Activo:",
        profile_rank: "Rango Operativo:",
        profile_reg_date: "Fecha de Registro:",
        profile_account_status: "Estado de Cuenta:",
        btn_terminate_sessions: "Cerrar Todas las Sesiones Activas",
        theme_light: "Claro",
        theme_dark: "Oscuro",
        menu_my_profile: "Mi Perfil",
        menu_help: "Ayuda & Soporte",
        menu_company_reg: "Registro de Compañía",
        help_support_chat: "Chat de Soporte Técnico",
        help_instruction: "Instrucciones & Manuales",
        help_test_regex: "Verificador de Patrones Regex",
        tab_report_error: "Reportar un Error",
        tab_leave_review: "Dejar una Reseña",
        click_attach: "Clic para adjuntar archivo",
        btn_cancel: "Cancelar",
        btn_send: "Enviar Mensaje",
        instruction_title: "Instrucciones & Manual Oficial",
        btn_close: "Cerrar",
        footer_copyright: "The Bunker Command OS © 2026 — Cloud Media Management",
        instruction_body: "The Bunker Command OS gestiona comunidades en Telegram con una automatización de nivel industrial. Conecta tus chats, administra permisos en tiempo real y audita licencias con pagos nativos en Telegram Stars.",
        instruction_steps_title: "🚀 Pasos iniciales:",
        instruction_step1: "1. Añade el bot como administrador en tu canal o grupo.",
        instruction_step2: "2. Sincroniza el ID desde el Estudio de Canales.",
        instruction_step3: "3. Configura tus tarifas en Stars (XTR).",
        company_reg_title: "Registro de Compañía",
        company_reg_body: "Bienvenido a la página de registro de organización del servicio The Bunker OS. El registro consta de varios pasos: especifica los datos de la organización y verifica tus credenciales.",
        company_reg_start: "Iniciar registro",
        regex_title: "Verificador de Expresión Regular",
        regex_pattern_label: "Expresión regular:",
        regex_string_label: "Texto a evaluar:",
        regex_lowercase_label: "Convertir a minúsculas",
        btn_reset: "Reiniciar",
        btn_test: "Probar",
        report_placeholder: "Describe el error o tu reseña...",
        select_your_channel: "Selecciona tu canal...",
        select_your_community: "Selecciona tu comunidad...",
        admin_stats_title: "Rendimiento de Administradores",
        top_users_title: "Top 10 Usuarios Activos (30 días)",
        active_modules_label: "Módulos Activos",
        btn_connect_channel: "➕ Conectar Canal",
        btn_connect_group: "➕ Conectar Comunidad",
        tariff_empty: "Plan de tarifa vacío 🔴",
        tariff_active: "Plan Activo 🟢",
        log_channel_label: "Canal de Registro:",
        status_enabled: "Habilitado",
        status_disabled: "Deshabilitado",
        login_title: "Acceso a The Bunker OS",
        login_subtitle: "Autentica tu identidad operativa para desbloquear el panel de comando.",
        login_or: "o",
        login_via_bot: "Iniciar sesión vía Bot",
        login_hint: "Se abrirá una ventana segura de Telegram para verificar tu identidad. No se solicitan contraseñas.",
        login_verifying: "🔐 Verificando identidad...",
        login_error: "⚠️ No se pudo verificar la sesión. Intenta de nuevo.",
        login_expired: "⚠️ Tu sesión expiró. Vuelve a iniciar sesión.",
        load_error: "Error al sincronizar con el servidor",
        btn_retry: "Reintentar conexión",
        action_clone_success: "¡Bot Clon desplegado y activo correctamente! 🟢",
        action_sentinel_success: "¡Centinela MTProto vinculado con éxito! 💎",
        action_purge_started: "Ghost Purge iniciada en segundo plano 🧹",

        // 📈 Analítica en vivo
        an_badge: "RADAR EN TIEMPO REAL",
        an_title: "Analítica de Comunidad",
        an_refresh: "Actualizar",
        an_toasts_on: "Alertas en vivo activadas 🔔",
        an_toasts_off: "Alertas en vivo silenciadas 🔕",
        an_empty: "Selecciona una comunidad para ver su analítica en vivo.",
        an_loading: "Compilando métricas...",
        an_err_forbidden: "No tienes permisos de administración sobre esta comunidad.",
        an_err_unavailable: "La analítica no está disponible en este momento.",
        an_updated: "Actualizado",
        an_kpi_dau: "Activos hoy (DAU)",
        an_kpi_wau: "7 días (WAU)",
        an_kpi_mau: "30 días (MAU)",
        an_kpi_stickiness: "Stickiness DAU/MAU",
        an_kpi_messages: "Mensajes hoy",
        an_vs_yesterday: "vs. ayer a esta hora",
        an_kpi_members: "Miembros",
        an_members_tracked: "en padrón",
        an_kpi_joins: "Altas 7d / 30d",
        an_kpi_retention: "Retención de cohortes",
        an_cohort_7d: "Cohorte 7 días",
        an_cohort_30d: "Cohorte 30 días",
        an_kpi_stars: "Recaudación Stars",
        an_stars_today: "hoy",
        an_stars_30d: "30 días",
        an_payments: "pagos",
        an_spark_messages: "Mensajes (30 días)",
        an_spark_active: "Usuarios activos (30 días)",
        an_spark_growth: "Altas de miembros (30 días)",
        an_peak_label: "Pico",
        an_heatmap_title: "Mapa de Calor 24/7",
        an_heatmap_empty: "Aún sin actividad suficiente",
        an_breakdown_title: "Desglose de Mensajes (30 días)",
        an_leaderboard_title: "Cuadro de Honor — Top 10",
        an_level: "Nivel",
        an_msgs_30d: "msgs/30d",
        an_lb_empty: "Aún sin actividad suficiente para el ranking",
        an_voice_title: "Sala de Audio",
        an_voice_idle: "Sin llamada activa",
        an_voice_live: "Llamada en curso",
        an_voice_present: "en sala",
        an_voice_mics: "micrófonos abiertos",
        an_feed_title: "Actividad en Vivo",
        an_feed_empty: "Esperando eventos en vivo...",
        kind_text: "texto",
        kind_media: "multimedia",
        kind_stickers_gifs: "sticker/GIF",
        kind_commands: "comando",
        kind_other: "otro",
        ws_live: "EN VIVO",
        ws_connecting: "Conectando…",
        ws_reconnecting: "Reconectando…",
        ws_offline: "Sin conexión",
        ws_paused: "En pausa",
        ws_denied: "Sin acceso",
        ws_idle: "Radar inactivo",
        toast_level_up_title: "¡Ascenso de nivel! 🏆",
        toast_level_up_body: "{name} alcanzó el nivel {level}",
        toast_msg_title_one: "Nuevo mensaje 💬",
        toast_msg_title_many: "{n} mensajes nuevos 💬",
        toast_voice_started: "Videochat iniciado 🎙️",
        toast_voice_ended: "Videochat finalizado 🔇",
        toast_payment_title: "Pago en Stars recibido ⭐",
        toast_payment_body: "+{stars} Stars de {name}",
        toast_reconnected: "Radar reconectado 🟢",
        feed_message: "{name} · {kind}",
        feed_level_up: "{name} subió al nivel {level}",
        feed_voice_joined: "{names} entró a la sala",
        feed_voice_left: "{n} salió(eron) de la sala",
        feed_payment: "{name} pagó {stars} ⭐"
    },
    en: {
        plans_title: "Community Memberships",
        basic_badge: "FREE TIER",
        basic_title: "BASIC Plan",
        basic_desc: "Limited moderation commands. No radar automation or priority support.",
        btn_free_active: "Active by Default",
        pro_badge: "MONTHLY PLAN",
        pro_title: "PRO Plan",
        pro_desc: "Total automation, voice moderation, and unlimited commands for your community.",
        ultra_badge: "UNLIMITED ACCESS",
        ultra_title: "ULTRA PRO",
        ultra_desc: "Advanced anti-ghost radar, max server priority, and direct support.",
        plans_stars_only: "100% in-app payment with Telegram Stars (XTR). Instant activation.",
        active_context: "Active Context:",
        stat_subs: "VIP Subscribers",
        stat_revenue: "Stars Revenue",
        live_sync: "Live sync",
        stat_source: "Real bot data",
        dash_telemetry: "Bunker Telemetry",
        online_tag: "Online 🟢",
        stat_verified: "Verified",
        stat_expelled: "Expelled",
        stat_purges: "Purges",
        perimeter_title: "Operational Perimeter",
        perimeter_sub: "24/7 Monitoring",
        captcha_label: "Captcha Customs:",
        autolower_label: "AutoLower Radar:",
        shield_label: "Screenshot Shield:",
        broadcast_label: "Recurring Broadcast:",
        linked_channels: "Connected Channels",
        linked_groups: "Connected Communities",
        sync: "Sync",
        syncing: "Syncing...",
        configure: "Configure",
        license_active: "Active 🟢",
        license_renew: "Renew",
        btn_logout: "Logout",
        no_channels: "No channels linked yet",
        no_groups: "No communities linked yet",
        no_subs: "No subscribers registered",
        aff_title: "Affiliate & Commission Network",
        aff_desc: "Share your promoter link. Whenever a community unlocks a PRO or ULTRA plan through your recommendation, receive direct Telegram Stars commissions.",
        nav_dash: "Telemetry & Stats",
        nav_channels: "Channel Studio",
        nav_groups: "Group Matrix",
        nav_watchdog: "Sub Watchdog",
        nav_plans: "Plans & Stars",
        nav_analytics: "Live Analytics",
        nav_aff: "Affiliate Network",
        studio_badge: "BROADCAST STUDIO",
        studio_title: "Channel Settings",
        btn_open_studio: "Save Settings",
        channel_owner_label: "Channel under your Creator ID:",
        vip_delivery_title: "VIP Link & Automatic Delivery",
        vip_target_label: "VIP Target (Private Channel / Resource):",
        stars_rate_label: "Rate in Stars (XTR):",
        duration_days_label: "Duration (Days):",
        perimeter_badge: "COMMUNITY PERIMETER",
        groups_title: "Group Control",
        shielded_mode: "Shielded Mode 🟢",
        group_owner_label: "Managed Community:",
        captcha_pro: "Captcha Customs Pro",
        captcha_desc: "Private checkpoint upon entry",
        autolower_title: "Microphone AutoLower (2%)",
        autolower_desc: "Background acoustic attenuation",
        shield_title: "Screen-Sharing Shield",
        shield_desc: "Blocks unauthorized screen share",
        linklock_title: "Web Links Lock",
        linklock_desc: "Instant purge of unapproved URLs",
        watchdog_badge: "MEMBER MONITOR",
        watchdog_title: "Subscription Watchdog",
        live_badge: "Live",
        watchdog_desc: "Real-time tracking of active members and renewal warnings before automated expulsion.",
        profile_balance_stars: "Stars Balance:",
        profile_discount: "Active Discount:",
        profile_rank: "Operational Rank:",
        profile_reg_date: "Registration Date:",
        profile_account_status: "Account Status:",
        btn_terminate_sessions: "Terminate All Active Sessions",
        theme_light: "Light",
        theme_dark: "Dark",
        menu_my_profile: "My profile",
        menu_help: "Help & Support",
        menu_company_reg: "Company registration",
        help_support_chat: "Technical support chat",
        help_instruction: "Instruction & Manuals",
        help_test_regex: "Test Regex / Pattern Checker",
        tab_report_error: "Report an error",
        tab_leave_review: "Leave a review",
        click_attach: "Click to attach file",
        btn_cancel: "Cancel",
        btn_send: "Send message",
        instruction_title: "Instructions & Official Manual",
        btn_close: "Close",
        footer_copyright: "The Bunker Command OS © 2026 — Cloud Media Management",
        instruction_body: "The Bunker Command OS manages Telegram communities with industrial-grade automation. Connect your chats, manage permissions in real time, and audit licenses with native Telegram Stars payments.",
        instruction_steps_title: "🚀 Initial steps:",
        instruction_step1: "1. Add the bot as admin in your channel or group.",
        instruction_step2: "2. Sync the ID from the Channel Studio.",
        instruction_step3: "3. Configure your rates in Stars (XTR).",
        company_reg_title: "Company Registration",
        company_reg_body: "Welcome to the organization registration page in The Bunker OS service. Registration consists of several steps: specify organization details and verify credentials.",
        company_reg_start: "Start registration",
        regex_title: "Regular Expression Check",
        regex_pattern_label: "Regular expression:",
        regex_string_label: "String to test:",
        regex_lowercase_label: "Cast to lowercase",
        btn_reset: "Reset",
        btn_test: "Test",
        report_placeholder: "Describe the error or review...",
        select_your_channel: "Select your channel...",
        select_your_community: "Select your community...",
        admin_stats_title: "Admin Performance",
        top_users_title: "Top 10 Active Users (30 days)",
        active_modules_label: "Active Modules",
        btn_connect_channel: "➕ Connect Channel",
        btn_connect_group: "➕ Connect Group",
        tariff_empty: "Tariff plan empty 🔴",
        tariff_active: "Plan Active 🟢",
        log_channel_label: "Log Channel:",
        status_enabled: "Enabled",
        status_disabled: "Disabled",
        login_title: "Access The Bunker OS",
        login_subtitle: "Authenticate your operator identity to unlock the command panel.",
        login_or: "or",
        login_via_bot: "Login via Bot",
        login_hint: "A secure Telegram window will open to verify your identity. No passwords required.",
        login_verifying: "🔐 Verifying identity...",
        login_error: "⚠️ Could not verify the session. Please try again.",
        login_expired: "⚠️ Your session expired. Please log in again.",
        load_error: "Failed to sync with server",
        btn_retry: "Retry connection",
        action_clone_success: "Clone Bot successfully deployed and active! 🟢",
        action_sentinel_success: "MTProto Sentinel successfully linked! 💎",
        action_purge_started: "Ghost Purge initiated in background 🧹",

        // 📈 Live analytics
        an_badge: "REAL-TIME RADAR",
        an_title: "Community Analytics",
        an_refresh: "Refresh",
        an_toasts_on: "Live alerts on 🔔",
        an_toasts_off: "Live alerts muted 🔕",
        an_empty: "Select a community to see its live analytics.",
        an_loading: "Compiling metrics...",
        an_err_forbidden: "You do not have admin permissions over this community.",
        an_err_unavailable: "Analytics are not available right now.",
        an_updated: "Updated",
        an_kpi_dau: "Active today (DAU)",
        an_kpi_wau: "7 days (WAU)",
        an_kpi_mau: "30 days (MAU)",
        an_kpi_stickiness: "DAU/MAU stickiness",
        an_kpi_messages: "Messages today",
        an_vs_yesterday: "vs. yesterday at this hour",
        an_kpi_members: "Members",
        an_members_tracked: "tracked",
        an_kpi_joins: "Joins 7d / 30d",
        an_kpi_retention: "Cohort retention",
        an_cohort_7d: "7-day cohort",
        an_cohort_30d: "30-day cohort",
        an_kpi_stars: "Stars revenue",
        an_stars_today: "today",
        an_stars_30d: "30 days",
        an_payments: "payments",
        an_spark_messages: "Messages (30 days)",
        an_spark_active: "Active users (30 days)",
        an_spark_growth: "New members (30 days)",
        an_peak_label: "Peak",
        an_heatmap_title: "24/7 Heatmap",
        an_heatmap_empty: "Not enough activity yet",
        an_breakdown_title: "Message Breakdown (30 days)",
        an_leaderboard_title: "Honor Board — Top 10",
        an_level: "Level",
        an_msgs_30d: "msgs/30d",
        an_lb_empty: "Not enough activity for the leaderboard yet",
        an_voice_title: "Voice Room",
        an_voice_idle: "No active call",
        an_voice_live: "Call in progress",
        an_voice_present: "in room",
        an_voice_mics: "open mics",
        an_feed_title: "Live Activity",
        an_feed_empty: "Waiting for live events...",
        kind_text: "text",
        kind_media: "media",
        kind_stickers_gifs: "sticker/GIF",
        kind_commands: "command",
        kind_other: "other",
        ws_live: "LIVE",
        ws_connecting: "Connecting…",
        ws_reconnecting: "Reconnecting…",
        ws_offline: "Offline",
        ws_paused: "Paused",
        ws_denied: "No access",
        ws_idle: "Radar idle",
        toast_level_up_title: "Level up! 🏆",
        toast_level_up_body: "{name} reached level {level}",
        toast_msg_title_one: "New message 💬",
        toast_msg_title_many: "{n} new messages 💬",
        toast_voice_started: "Voice chat started 🎙️",
        toast_voice_ended: "Voice chat ended 🔇",
        toast_payment_title: "Stars payment received ⭐",
        toast_payment_body: "+{stars} Stars from {name}",
        toast_reconnected: "Radar reconnected 🟢",
        feed_message: "{name} · {kind}",
        feed_level_up: "{name} reached level {level}",
        feed_voice_joined: "{names} joined the room",
        feed_voice_left: "{n} left the room",
        feed_payment: "{name} paid {stars} ⭐"
    }
};