/* ==========================================================================
   THE BUNKER — COMMAND OS
   config.js — Constantes de Entorno, Tarifas e Internacionalización (i18n)
   Fase 5/6/7/8: Radar en vivo, analítica, checkout Stars (XTR), Estudio de Canales reactivo,
   sesión estricta por initData y gestión interactiva de Planes de Membresía del canal.
   v8.2: modal nativo del canal de registro, sincronización real de chats, difusión personalizada
   con acciones rápidas y consola de control de grupos operativa.
   v8.3: generador CRUD de planes de canal y consola de programación 1:1 (Aduana, Acústica,
   Propinas y Perímetro) sobre las mismas columnas que lee el bot.
   ========================================================================== */

export const CONFIG = {
    BOT_USERNAME: 'thebunkerapp_bot',
    WEBAPP_URL: 'https://thebunkerapp2.netlify.app/',
    API_BASE: 'https://the-bunker-bot-production.up.railway.app',

    // 📡 Radar en vivo: el WebSocket del backend vive en el mismo dominio de Railway
    // (ruta /ws/radar/{chat_id}). Debe usar wss:// porque la Mini App se sirve por HTTPS.
    WS_BASE: 'wss://the-bunker-bot-production.up.railway.app',

    // Un único medio de pago: Telegram Stars (XTR). Sin pasarelas externas ni precios fiat.
    PRICES: {
        pro:   { stars: 300 },
        ultra: { stars: 600 }
    },

    // ⚡ Parámetros del cliente WebSocket (BunkerWebSocketClient)
    WS: {
        // 'query' → ?init_data= / ?token= en la URL | 'frame' → primer frame {action:'auth'}
        // (evita que las credenciales aparezcan en los logs de acceso del proxy).
        AUTH_MODE: 'query',
        HEARTBEAT_MS: 20000,        // ping cada 20 s (el servidor corta a los 90 s de silencio)
        PONG_TIMEOUT_MS: 10000,     // sin ningún mensaje tras un ping → conexión muerta
        BACKOFF_BASE_MS: 1000,      // reconexión exponencial: 1 s, 2 s, 4 s ... hasta el tope
        BACKOFF_MAX_MS: 30000,
        BACKOFF_FACTOR: 2,
        RATE_LIMITED_MIN_MS: 30000, // cierre 4429 (sala llena / demasiadas sesiones)
        HIDDEN_PAUSE_MS: 60000      // pausa la conexión si la Mini App lleva 60 s en segundo plano
    },

    // 🎬 Estudio de Canales: guardado reactivo (límites alineados con Telegram Stars)
    STUDIO: {
        AUTOSAVE_MS: 900,       // espera tras la última pulsación antes de guardar solo
        PRICE_MIN: 1,           // una factura XTR admite de 1 a 10 000 Stars
        PRICE_MAX: 10000,
        DAYS_MIN: 1,
        DAYS_MAX: 365,
        LINK_MAX: 256,
        DEFAULT_PRICE: 150,
        DEFAULT_DAYS: 30,
        // Difusión personalizada (v8.2) — mismos límites que valida channel_plans_api.py
        PROMO_MAX: 1000,
        BROADCAST_INTERVALS: [6, 12, 24, 48],
        DEFAULT_INTERVAL: 12
    },

    // ⚙️ Consola de control de grupos (v8.2)
    CONSOLE: {
        TOAST_MS: 3600,
        SWITCH_KEYS: ['captcha', 'autolower', 'shield', 'linklock']
    },

    // ➕ Generador de planes del Estudio (v8.3) — mismos límites que channel_plans_api.validate_plan_payload
    PLAN_FORM: {
        NAME_MAX: 64,
        PRICE_MIN: 1,
        PRICE_MAX: 10000,
        DAYS_MIN: 1,
        DAYS_MAX: 365,
        LINK_MAX: 256,
        PROMO_MAX: 1000,
        DEFAULT_PRICE: 150,
        DEFAULT_DAYS: 30
    },

    // 🎛️ Consola de programación 1:1 (v8.3) — mismos rangos que database.validate_chat_configuration
    CHAT_CONFIG: {
        SECTIONS: ['aduana', 'acoustic', 'tips', 'perimeter'],
        CAPTCHA_MODES: ['button', 'math'],
        CAPTCHA_TIMEOUTS: [30, 60, 120, 300],
        WELCOME_MAX: 1000,
        WELCOME_VARIABLES: ['name', 'username', 'title'],
        AUTOLOWER_PCT_MIN: 1,
        AUTOLOWER_PCT_MAX: 10,
        STARS_MIN: 1,
        STARS_MAX: 10000,
        TIP_PRESETS_MAX: 6,
        ANTIFLOOD_RATE_MIN: 3,
        ANTIFLOOD_RATE_MAX: 50,
        ANTIFLOOD_WINDOW_MIN: 5,
        ANTIFLOOD_WINDOW_MAX: 120,
        // Interruptor heredado (v8.2) → campo de la configuración
        LEGACY_SWITCHES: { captcha: 'captcha_enabled', autolower: 'autolower_enabled', shield: 'shield_enabled', linklock: 'linklock_enabled' }
    },

    // 💎 Planes de Membresía del canal
    PLANS: {
        LIST_TIMEOUT_MS: 12000,
        CONFIRM_TIMEOUT_MS: 6000,   // la confirmación inline (eliminar / difundir) se cancela sola
        TOAST_MS: 3200
    },

    // 📈 Analítica de comunidad
    ANALYTICS: {
        REST_TIMEOUT_MS: 12000,
        REFRESH_MIN_MS: 20000,          // mínimo entre refrescos pedidos tras eventos en vivo
        FEED_MAX_ITEMS: 30,
        MESSAGE_TOAST_WINDOW_MS: 2500,  // agrupa los mensajes en vivo en un único aviso
        TOAST_MAX_VISIBLE: 3
    }
};

export const translations = {
    es: {
        plans_title: "Membresías de Comunidad",
        basic_badge: "ACCESO GRATUITO",
        basic_title: "Plan BÁSICO",
        basic_desc: "Comandos de moderación limitados. Sin automatización de radar ni soporte prioritario.",
        btn_free_active: "Activo por defecto",
        pro_badge: "PLAN MENSUAL",
        pro_title: "Plan PRO",
        pro_desc: "Automatización total, moderación de voz y comandos ilimitados para tu comunidad.",
        ultra_badge: "ACCESO ILIMITADO",
        ultra_title: "ULTRA PRO",
        ultra_desc: "Radar avanzado anti-fantasmas, prioridad máxima en servidores y soporte directo.",
        plans_stars_only: "Pago 100% in-app con Telegram Stars (XTR). Activación inmediata.",
        active_context: "Entorno Activo:",
        stat_subs: "Suscriptores VIP",
        stat_revenue: "Ingresos Stars",
        live_sync: "Sincronización en vivo",
        stat_source: "Datos reales del bot",
        dash_telemetry: "Telemetría del Búnker",
        online_tag: "En Línea 🟢",
        stat_verified: "Verificados",
        stat_expelled: "Expulsados",
        stat_purges: "Purgas",
        perimeter_title: "Perímetro Operativo",
        perimeter_sub: "Supervisión 24/7",
        captcha_label: "Aduana Captcha:",
        autolower_label: "Radar AutoLower:",
        shield_label: "Escudo Antinota:",
        broadcast_label: "Difusión Recurrente:",
        linked_channels: "Canales Conectados",
        linked_groups: "Comunidades Conectadas",
        sync: "Sincronizar",
        syncing: "Sincronizando...",
        configure: "Configurar",
        license_active: "Activa 🟢",
        license_renew: "Renovar",
        btn_logout: "Cerrar Sesión",
        no_channels: "Sin canales vinculados aún",
        no_groups: "Sin comunidades vinculadas aún",
        no_subs: "Sin suscriptores registrados",
        aff_title: "Red de Afiliados & Comisiones",
        aff_desc: "Comparte tu enlace único de promotor. Cada vez que una comunidad adquiera un plan PRO o ULTRA a través de tu recomendación, recibes comisiones instantáneas en Telegram Stars directo a tu balance.",
        nav_dash: "Telemetría & Stats",
        nav_channels: "Estudio de Canales",
        nav_groups: "Matriz de Grupos",
        nav_watchdog: "Auditor Suscripciones",
        nav_plans: "Membresías & Stars",
        nav_analytics: "Analítica en Vivo",
        nav_aff: "Red de Afiliados",
        studio_badge: "ESTUDIO DE BROADCAST",
        studio_title: "Ajustes del Canal",
        btn_open_studio: "Guardar Ajustes",
        channel_owner_label: "Canal Bajo tu ID de Creador:",
        vip_delivery_title: "Enlace VIP & Entrega Automática",
        vip_target_label: "Destino VIP (Canal Privado / Recurso):",
        stars_rate_label: "Tarifa en Stars (XTR):",
        duration_days_label: "Duración (Días):",
        perimeter_badge: "PERÍMETRO COMUNITARIO",
        groups_title: "Control de Grupos",
        shielded_mode: "Modo Blindado 🟢",
        group_owner_label: "Comunidad Administrada:",
        captcha_pro: "Aduana Captcha Pro",
        captcha_desc: "Desafío privado antes de ingresar",
        autolower_title: "AutoLower de Micrófonos (2%)",
        autolower_desc: "Atenuación acústica de fondo",
        shield_title: "Escudo Antinota",
        shield_desc: "Corte de pantalla compartida",
        linklock_title: "Cerradura de Enlaces Web",
        linklock_desc: "Purga inmediata de URLs no permitidas",
        watchdog_badge: "MONITOR DE MIEMBROS",
        watchdog_title: "Aviso de Suscripciones",
        live_badge: "En Vivo",
        watchdog_desc: "Supervisa en tiempo real el tiempo restante de cada miembro suscrito y las alertas de renovación antes del Auto-Kick automático.",
        profile_balance_stars: "Balance Stars:",
        profile_discount: "Descuento Activo:",
        profile_rank: "Rango Operativo:",
        profile_reg_date: "Fecha de Registro:",
        profile_account_status: "Estado de Cuenta:",
        btn_terminate_sessions: "Cerrar Todas las Sesiones Activas",
        theme_light: "Claro",
        theme_dark: "Oscuro",
        menu_my_profile: "Mi Perfil",
        menu_help: "Ayuda & Soporte",
        help_support_chat: "Chat de Soporte Técnico",
        help_instruction: "Instrucciones & Manuales",
        help_test_regex: "Verificador de Patrones Regex",
        tab_report_error: "Reportar un Error",
        tab_leave_review: "Dejar una Reseña",
        click_attach: "Clic para adjuntar archivo",
        btn_cancel: "Cancelar",
        btn_send: "Enviar Mensaje",
        instruction_title: "Instrucciones & Manual Oficial",
        btn_close: "Cerrar",
        footer_copyright: "The Bunker Command OS © 2026 — Cloud Media Management",
        instruction_body: "The Bunker Command OS gestiona comunidades en Telegram con una automatización de nivel industrial. Conecta tus chats, administra permisos en tiempo real y audita licencias con pagos nativos en Telegram Stars.",
        instruction_steps_title: "🚀 Pasos iniciales:",
        instruction_step1: "1. Añade el bot como administrador en tu canal o grupo.",
        instruction_step2: "2. Sincroniza el ID desde el Estudio de Canales.",
        instruction_step3: "3. Configura tus tarifas en Stars (XTR).",
        regex_title: "Verificador de Expresión Regular",
        regex_pattern_label: "Expresión regular:",
        regex_string_label: "Texto a evaluar:",
        regex_lowercase_label: "Convertir a minúsculas",
        btn_reset: "Reiniciar",
        btn_test: "Probar",
        report_placeholder: "Describe el error o tu reseña...",
        select_your_channel: "Selecciona tu canal...",
        select_your_community: "Selecciona tu comunidad...",
        admin_stats_title: "Rendimiento de Administradores",
        top_users_title: "Top 10 Usuarios Activos (30 días)",
        btn_connect_channel: "➕ Conectar Canal",
        btn_connect_group: "➕ Conectar Comunidad",
        tariff_empty: "Plan de tarifa vacío 🔴",
        tariff_active: "Plan Activo 🟢",
        log_channel_label: "Canal de Registro:",
        status_enabled: "Habilitado",
        status_disabled: "Deshabilitado",
        login_title: "Acceso a The Bunker OS",
        login_subtitle: "Autentica tu identidad operativa para desbloquear el panel de comando.",
        login_or: "o",
        login_via_bot: "Iniciar sesión vía Bot",
        login_hint: "Se abrirá una ventana segura de Telegram para verificar tu identidad. No se solicitan contraseñas.",
        login_verifying: "🔐 Verificando identidad...",
        login_error: "⚠️ No se pudo verificar la sesión. Intenta de nuevo.",
        login_expired: "⚠️ Tu sesión expiró. Vuelve a iniciar sesión.",
        load_error: "Error al sincronizar con el servidor",
        btn_retry: "Reintentar conexión",
        action_clone_success: "¡Bot Clon desplegado y activo correctamente! 🟢",
        action_sentinel_success: "¡Centinela MTProto vinculado con éxito! 💎",
        action_purge_started: "Ghost Purge iniciada en segundo plano 🧹",

        // 📈 Analítica en vivo
        an_badge: "RADAR EN TIEMPO REAL",
        an_title: "Analítica de Comunidad",
        an_refresh: "Actualizar",
        an_toasts_on: "Alertas en vivo activadas 🔔",
        an_toasts_off: "Alertas en vivo silenciadas 🔕",
        an_empty: "Selecciona una comunidad para ver su analítica en vivo.",
        an_loading: "Compilando métricas...",
        an_err_forbidden: "No tienes permisos de administración sobre esta comunidad.",
        an_err_unavailable: "La analítica no está disponible en este momento.",
        an_updated: "Actualizado",
        an_kpi_dau: "Activos hoy (DAU)",
        an_kpi_wau: "7 días (WAU)",
        an_kpi_mau: "30 días (MAU)",
        an_kpi_stickiness: "Stickiness DAU/MAU",
        an_kpi_messages: "Mensajes hoy",
        an_vs_yesterday: "vs. ayer a esta hora",
        an_kpi_members: "Miembros",
        an_members_tracked: "en padrón",
        an_kpi_joins: "Altas 7d / 30d",
        an_kpi_retention: "Retención de cohortes",
        an_cohort_7d: "Cohorte 7 días",
        an_cohort_30d: "Cohorte 30 días",
        an_kpi_stars: "Recaudación Stars",
        an_stars_today: "hoy",
        an_stars_30d: "30 días",
        an_payments: "pagos",
        an_spark_messages: "Mensajes (30 días)",
        an_spark_active: "Usuarios activos (30 días)",
        an_spark_growth: "Altas de miembros (30 días)",
        an_peak_label: "Pico",
        an_heatmap_title: "Mapa de Calor 24/7",
        an_heatmap_empty: "Aún sin actividad suficiente",
        an_breakdown_title: "Desglose de Mensajes (30 días)",
        an_leaderboard_title: "Cuadro de Honor — Top 10",
        an_level: "Nivel",
        an_msgs_30d: "msgs/30d",
        an_lb_empty: "Aún sin actividad suficiente para el ranking",
        an_voice_title: "Sala de Audio",
        an_voice_idle: "Sin llamada activa",
        an_voice_live: "Llamada en curso",
        an_voice_present: "en sala",
        an_voice_mics: "micrófonos abiertos",
        an_feed_title: "Actividad en Vivo",
        an_feed_empty: "Esperando eventos en vivo...",
        kind_text: "texto",
        kind_media: "multimedia",
        kind_stickers_gifs: "sticker/GIF",
        kind_commands: "comando",
        kind_other: "otro",
        ws_live: "Conectado 🟢",
        ws_connecting: "Conectando 🟡",
        ws_reconnecting: "Reconectando 🟡",
        ws_offline: "Sin conexión 🔴",
        ws_paused: "En pausa ⚪",
        ws_denied: "Sin acceso 🔴",
        ws_idle: "Radar inactivo",
        toast_level_up_title: "¡Ascenso de nivel! 🏆",
        toast_level_up_body: "{name} alcanzó el nivel {level}",
        toast_msg_title_one: "Nuevo mensaje 💬",
        toast_msg_title_many: "{n} mensajes nuevos 💬",
        toast_voice_started: "Videochat iniciado 🎙️",
        toast_voice_ended: "Videochat finalizado 🔇",
        toast_payment_title: "Pago en Stars recibido ⭐",
        toast_payment_body: "+{stars} Stars de {name}",
        toast_reconnected: "Radar reconectado 🟢",
        feed_message: "{name} · {kind}",
        feed_level_up: "{name} subió al nivel {level}",
        feed_voice_joined: "{names} entró a la sala",
        feed_voice_left: "{n} salió(eron) de la sala",
        feed_payment: "{name} pagó {stars} ⭐",

        // 🎬 Estudio de Canales (guardado reactivo)
        tariff_plan_label: "Plan Tarifario",
        studio_pick_channel: "Selecciona primero un canal bajo tu ID de creador.",
        studio_status_dirty: "Cambios sin guardar…",
        studio_status_saving: "Guardando…",
        studio_status_saved: "Guardado y verificado ✓ {time}",
        studio_status_saved_unverified: "Guardado ✓ {time}",
        studio_status_mismatch: "⚠️ Guardado, pero el servidor devuelve otros valores ({values}). Revisa el plan del canal.",
        studio_status_error: "❌ No se pudo guardar: {error}",
        studio_status_invalid: "Revisa los campos marcados en rojo",
        studio_status_forbidden: "❌ No tienes permisos sobre este canal",
        studio_err_link: "Usa un enlace https://, t.me/… o @alias",
        studio_err_link_long: "Máximo {max} caracteres",
        studio_err_price: "Un número entero entre {min} y {max} Stars",
        studio_err_days: "Un número entero entre {min} y {max} días",
        studio_days_unit: "d",

        // 🔐 Sesión de Telegram
        session_expired_title: "Sesión caducada",
        session_expired_body: "Tu sesión de Telegram ya no es válida. Cierra y vuelve a abrir la Mini App desde el bot.",
        session_expired_btn: "Cerrar",

        // 🎙️ Centinela
        sentinel_phone_hint: "El acceso por teléfono se completa desde el bot en privado. Aquí pega la String Session.",

        // 💎 Planes de Membresía del canal
        plans_badge: "MEMBRESÍAS",
        plans_title: "Planes Activos del Canal",
        plans_refresh: "Actualizar",
        plans_select_channel: "Selecciona un canal para ver sus planes de membresía.",
        plans_loading: "Cargando planes...",
        plans_empty: "Este canal aún no tiene planes de membresía. Créalos desde el panel del canal en el bot (💎 Planes de Membresía).",
        plans_load_error: "No se pudieron cargar los planes",
        plans_count: "{active} activos · {total} en total",
        plans_subscribers: "{n} suscriptores activos",
        plans_status_active: "Activo 🟢",
        plans_status_paused: "Pausado 🔴",
        plans_days: "{n} días",
        plans_media_photo: "Foto",
        plans_media_video: "Vídeo",
        plans_media_animation: "GIF",
        plans_btn_preview: "Vista",
        plans_btn_pause: "Pausar",
        plans_btn_activate: "Activar",
        plans_btn_broadcast: "Difundir",
        plans_btn_link: "Enlace",
        plans_btn_copy: "Copiar",
        plans_btn_delete: "Borrar",
        plans_tip_preview: "Previsualizar tarjeta",
        plans_tip_pause: "Pausar plan",
        plans_tip_activate: "Activar plan",
        plans_tip_broadcast: "Difundir en el canal",
        plans_tip_link: "Generar enlace de compra",
        plans_tip_copy: "Copiar enlace de compra",
        plans_tip_delete: "Eliminar plan",
        plans_confirm_delete: "¿Eliminar «{name}»? Esta acción no se puede deshacer.",
        plans_confirm_delete_yes: "Sí, eliminar",
        plans_confirm_broadcast: "¿Publicar «{name}» en el canal ahora?",
        plans_confirm_broadcast_yes: "Sí, publicar",
        plans_confirm_no: "Cancelar",
        plans_link_label: "Enlace de compra con entrega automática",
        plans_link_hint: "Quien pague con Stars recibe automáticamente su enlace de acceso VIP de un solo uso.",
        plans_toast_activated: "Plan activado 🟢",
        plans_toast_paused: "Plan pausado 🔴",
        plans_toast_deleted: "Plan eliminado 🗑️",
        plans_toast_broadcast: "Anuncio publicado en el canal 📢",
        plans_toast_link_copied: "Enlace de compra copiado 🔗",
        plans_toast_link_ready: "Enlace generado: pulsa Copiar 🔗",
        plans_toast_link_local: "Enlace generado localmente (tu servidor no expone esta función)",
        plans_toast_error: "No se pudo completar: {error}",
        plans_err_missing: "Tu servidor aún no expone esta función. Actualiza el backend (channel_plans_api).",
        plans_err_forbidden: "No tienes permisos sobre este canal.",
        plans_err_inactive: "Activa el plan primero: un plan pausado no se puede comprar ni difundir.",
        plans_toast_copy_failed: "No se pudo copiar: mantén pulsado el enlace y cópialo.",
        plans_preview_title: "Vista previa del anuncio",
        plans_preview_hint: "Así verán tu plan en Telegram.",
        plans_preview_duration: "Duración",
        plans_preview_price: "Precio",
        plans_preview_subscribe: "⭐ Suscribirme ({n} Stars)",
        plans_preview_resource: "🔗 Acceder al Recurso VIP",
        plans_preview_media: "Incluye: {type}",

        // --- v8.2 · Modal del Canal de Registro ---
        logm_badge: "AUDITORÍA",
        logm_title: "Canal de Registro",
        logm_desc: "Los eventos de moderación de esta comunidad (expulsiones, captcha, purgas) se publicarán en este canal.",
        logm_label: "ID numérico o @alias del canal",
        logm_placeholder: "-1001234567890 o @MiCanalDeLogs",
        logm_help: "El bot debe ser administrador del canal con permiso para publicar y tú debes administrarlo. Deja el campo vacío y guarda para desactivar el registro.",
        logm_current: "Actual:",
        logm_none: "Sin canal de registro",
        logm_community: "Comunidad:",
        logm_save: "Guardar",
        logm_cancel: "Cancelar",
        logm_saving: "Verificando…",
        logm_err_format: "Usa un @alias público (5-32 caracteres) o el ID numérico del canal (-100…).",
        logm_toast_saved: "Canal de registro activado ✅",
        logm_toast_disabled: "Canal de registro desactivado",
        logm_toast_error: "No se pudo guardar el canal de registro",

        // --- v8.2 · Sincronización de chats ---
        sync_toast_title: "Sincronización completada",
        sync_toast_body: "{channels} canales · {groups} comunidades · {linked} vinculadas ahora",
        sync_toast_throttled: "Ya sincronizaste hace un momento: se muestran los datos actuales.",
        sync_toast_error: "Error de sincronización",

        // --- v8.2 · Difusión personalizada del Estudio ---
        bc_section_title: "Difusión Automática de Promoción",
        bc_ready: "Ultra Ready 🟢",
        bc_status_on: "Programada cada {h} h 🟢",
        bc_status_off: "Sin programar ⚪",
        bc_target_label: "Chat Destino (@alias o ID):",
        bc_target_placeholder: "@MiComunidad",
        bc_target_hint: "Vacío = sin difusión automática; \"Difundir Ahora\" publicará en el propio canal.",
        bc_interval_label: "Intervalo de Repetición:",
        bc_interval_6: "Cada 6 Horas",
        bc_interval_12: "Cada 12 Horas",
        bc_interval_24: "Cada 24 Horas (Diario)",
        bc_interval_48: "Cada 48 Horas",
        bc_promo_label: "Texto del Mensaje Promocional / Payload:",
        bc_promo_placeholder: "¡Accede a nuestro contenido VIP con beneficios exclusivos aquí! Admite <b>negrita</b>, <i>cursiva</i>, <u>subrayado</u>, <s>tachado</s> y <code>código</code>.",
        bc_btn_preview: "Vista Previa",
        bc_btn_send: "Difundir Ahora",
        bc_btn_clear: "Limpiar",
        bc_err_target: "Usa un @alias público (5-32 caracteres) o el ID numérico del chat.",
        bc_err_promo_long: "Máximo {max} caracteres.",
        bc_err_promo_required: "Escribe el texto promocional para difundir en el chat destino.",
        bc_err_interval: "Elige un intervalo válido.",
        bc_err_empty: "Escribe primero el texto promocional.",
        bc_preview_title: "Vista previa de la difusión",
        bc_preview_hint: "Así se publicará tu promoción en Telegram.",
        bc_preview_target: "Destino: {target}",
        bc_preview_target_self: "Destino: este canal",
        bc_preview_schedule: "Repetición: cada {h} h",
        bc_preview_schedule_off: "Repetición: desactivada (sin chat destino)",
        bc_preview_buy: "⭐ Obtener Acceso (Stars)",
        bc_preview_buy_note: "El botón de compra se añade si el canal tiene un plan activo.",
        bc_confirm_send: "¿Publicar ahora la promoción en {target}?",
        bc_confirm_clear: "¿Limpiar la configuración de difusión? Se desactivará la difusión automática.",
        bc_toast_sent: "Promoción publicada en {target} 📢",
        bc_toast_error: "No se pudo difundir: {error}",
        bc_toast_cleared: "Difusión restablecida a los valores por defecto",
        bc_toast_save_first: "Corrige los campos marcados antes de difundir.",

        // --- v8.2 · Consola de control de grupos ---
        gc_pick_first: "Selecciona primero una comunidad administrada.",
        gc_switch_on: "ACTIVO 🟢",
        gc_switch_off: "BLOQUEADO 🔴",
        gc_switch_loading: "Sincronizando…",
        gc_switch_toast_on: "{name}: activado",
        gc_switch_toast_off: "{name}: desactivado",
        gc_switch_toast_error: "No se pudo cambiar {name}: {error}",
        gc_ultra_title: "Herramientas Ultra & Clones MTProto",
        gc_clone_label: "Token de Bot Clon (BotFather):",
        gc_btn_deploy: "Desplegar",
        gc_sentinel_label: "Centinela Acústico MTProto:",
        gc_btn_sentinel: "Conectar Centinela",
        gc_btn_purge: "Ejecutar Ghost Purge (Cuentas Fantasma)",
        gc_running: "Procesando…",
        gc_clone_err_token: "Ingresa el Bot Token generado en @BotFather.",
        gc_clone_err_format: "El token no tiene el formato de @BotFather (123456789:ABC…).",
        gc_clone_toast_ok: "Bot Clon @{name} desplegado y activo 🚀",
        gc_clone_toast_error: "Error al desplegar el clon: {error}",
        gc_sentinel_err_session: "Pega la String Session generada para tu Centinela MTProto.",
        gc_sentinel_toast_ok: "Centinela MTProto conectado 📡",
        gc_sentinel_toast_error: "Error al conectar el centinela: {error}",
        gc_purge_confirm: "💀 ¿Iniciar la purga de cuentas fantasma y perfiles eliminados en esta comunidad?",
        gc_purge_toast_ok: "Ghost Purge en ejecución en segundo plano ⚡",
        gc_purge_toast_error: "Error al iniciar Ghost Purge: {error}",
        gc_err_generic: "Fallo de comunicación",

        // --- v8.3 · Generador de planes ---
        pf_title: "Generador de Planes VIP",
        pf_desc: "Crea un plan real en el catálogo del canal: se cobra en Telegram Stars y el bot entrega el acceso automáticamente.",
        pf_name_label: "Nombre del Plan:",
        pf_name_placeholder: "VIP Mensual",
        pf_price_label: "Tarifa en Stars (XTR):",
        pf_days_label: "Duración (Días):",
        pf_link_label: "Destino VIP (opcional):",
        pf_link_placeholder: "https://t.me/+... o @alias (botón extra tras el pago)",
        pf_promo_label: "Texto Promocional / Payload:",
        pf_promo_placeholder: "Describe el beneficio. Admite <b>negrita</b>, <i>cursiva</i>, <u>subrayado</u>, <s>tachado</s> y <code>código</code>.",
        pf_btn_create: "Crear y Activar",
        pf_btn_preview: "Previsualizar",
        pf_btn_broadcast: "Difundir",
        pf_btn_clear: "Limpiar",
        pf_creating: "Creando…",
        pf_err_name: "Entre 1 y {max} caracteres.",
        pf_err_price: "Un número entero entre {min} y {max} Stars.",
        pf_err_days: "Un número entero entre {min} y {max} días.",
        pf_err_link: "Usa un enlace https://, t.me/+… o un @alias.",
        pf_err_promo: "Máximo {max} caracteres.",
        pf_toast_created: "Plan «{name}» creado y activo 💎",
        pf_toast_created_body: "Entrega verificada: el bot puede invitar a los compradores.",
        pf_toast_created_warn: "Plan creado, pero el bot NO puede invitar en el canal: hazlo administrador con permiso de invitar.",
        pf_toast_error: "No se pudo crear el plan: {error}",
        pf_toast_invalid: "Revisa los campos marcados del plan.",
        pf_toast_cleared: "Formulario de plan vaciado",
        pf_confirm_broadcast_new: "Se creará y activará el plan «{name}» y se publicará en el canal. ¿Continuar?",
        pf_confirm_broadcast: "¿Publicar ahora el plan «{name}» en el canal?",
        pf_check_link: "Enlace de verificación (1 uso · 24 h)",

        // --- v8.3 · Consola de programación ---
        cfg_title: "Programación del Bot",
        cfg_desc: "Cada cambio rige el comportamiento del bot en la comunidad al instante.",
        cfg_loading: "Cargando configuración…",
        cfg_pick: "Selecciona una comunidad para programar el bot.",
        cfg_save: "Guardar",
        cfg_saving: "Guardando…",
        cfg_status_saved: "Guardado ✓ {time}",
        cfg_status_dirty: "Cambios sin guardar",
        cfg_status_invalid: "Revisa los campos marcados",
        cfg_status_error: "Error: {error}",
        cfg_status_remote: "Actualizado desde otro dispositivo",
        cfg_toast_saved: "{section}: configuración guardada ✅",
        cfg_toast_error: "{section}: no se pudo guardar — {error}",
        cfg_toast_switch_on: "{name}: activado",
        cfg_toast_switch_off: "{name}: desactivado",
        cfg_switch_on: "ON",
        cfg_switch_off: "OFF",
        cfg_sec_aduana: "Aduana & Bienvenida",
        cfg_sec_aduana_desc: "Reto de verificación para nuevos miembros y mensaje de bienvenida.",
        cfg_sec_acoustic: "Acústica & Videochat",
        cfg_sec_acoustic_desc: "Atenuación automática, escudo de pantalla y tarifas del videochat.",
        cfg_sec_tips: "Propinas & Monetización",
        cfg_sec_tips_desc: "Aportes voluntarios en Telegram Stars para la comunidad.",
        cfg_sec_perimeter: "Perímetro & Filtros",
        cfg_sec_perimeter_desc: "Enlaces, inundación de mensajes y limpieza de avisos de servicio.",
        cfg_captcha_enabled: "Aduana Captcha Pro",
        cfg_captcha_mode: "Modo de Reto:",
        cfg_captcha_mode_button: "Botón simple («Soy humano»)",
        cfg_captcha_mode_math: "Desafío aritmético",
        cfg_captcha_timeout: "Tiempo Límite:",
        cfg_seconds: "{n} s",
        cfg_custom_welcome: "Mensaje de Bienvenida:",
        cfg_welcome_placeholder: "¡Bienvenido {name} a {title}! Lee las reglas fijadas.",
        cfg_welcome_vars: "Variables:",
        cfg_autolower_enabled: "AutoLower de Micrófonos",
        cfg_autolower_pct: "Atenuación:",
        cfg_shield_enabled: "Escudo Antinota (Screen-Sharing Shield)",
        cfg_micvip_price: "Pase VIP 24h (MicVIP) ⭐:",
        cfg_speaker_price: "Turno Prioritario (Cola AMA) ⭐:",
        cfg_tips_enabled: "Propinas en Stars",
        cfg_tips_presets: "Montos rápidos (separados por coma):",
        cfg_tips_presets_placeholder: "15, 50, 100, 250, 500",
        cfg_custom_tips_allowed: "Permitir monto libre",
        cfg_linklock_enabled: "Cerradura de Enlaces (LinkLock)",
        cfg_antiflood_enabled: "Anti-Flood",
        cfg_antiflood_rate: "Mensajes permitidos:",
        cfg_antiflood_window: "por ventana de (s):",
        cfg_service_cleaner_enabled: "Purga de mensajes de servicio (uniones/salidas)",
        cfg_err_bool: "Valor inválido.",
        cfg_err_range: "Entre {min} y {max}.",
        cfg_err_presets: "Entre 1 y {max} montos enteros de 1 a 10000.",
        cfg_err_welcome_long: "Máximo {max} caracteres.",
        cfg_err_welcome_var: "Variable desconocida {{var}}. Usa {name}, {username} o {title}.",
        cfg_actions_title: "Herramientas Tácticas"
    },
    en: {
        plans_title: "Community Memberships",
        basic_badge: "FREE TIER",
        basic_title: "BASIC Plan",
        basic_desc: "Limited moderation commands. No radar automation or priority support.",
        btn_free_active: "Active by Default",
        pro_badge: "MONTHLY PLAN",
        pro_title: "PRO Plan",
        pro_desc: "Total automation, voice moderation, and unlimited commands for your community.",
        ultra_badge: "UNLIMITED ACCESS",
        ultra_title: "ULTRA PRO",
        ultra_desc: "Advanced anti-ghost radar, max server priority, and direct support.",
        plans_stars_only: "100% in-app payment with Telegram Stars (XTR). Instant activation.",
        active_context: "Active Context:",
        stat_subs: "VIP Subscribers",
        stat_revenue: "Stars Revenue",
        live_sync: "Live sync",
        stat_source: "Real bot data",
        dash_telemetry: "Bunker Telemetry",
        online_tag: "Online 🟢",
        stat_verified: "Verified",
        stat_expelled: "Expelled",
        stat_purges: "Purges",
        perimeter_title: "Operational Perimeter",
        perimeter_sub: "24/7 Monitoring",
        captcha_label: "Captcha Customs:",
        autolower_label: "AutoLower Radar:",
        shield_label: "Screenshot Shield:",
        broadcast_label: "Recurring Broadcast:",
        linked_channels: "Connected Channels",
        linked_groups: "Connected Communities",
        sync: "Sync",
        syncing: "Syncing...",
        configure: "Configure",
        license_active: "Active 🟢",
        license_renew: "Renew",
        btn_logout: "Logout",
        no_channels: "No channels linked yet",
        no_groups: "No communities linked yet",
        no_subs: "No subscribers registered",
        aff_title: "Affiliate & Commission Network",
        aff_desc: "Share your promoter link. Whenever a community unlocks a PRO or ULTRA plan through your recommendation, receive direct Telegram Stars commissions.",
        nav_dash: "Telemetry & Stats",
        nav_channels: "Channel Studio",
        nav_groups: "Group Matrix",
        nav_watchdog: "Sub Watchdog",
        nav_plans: "Plans & Stars",
        nav_analytics: "Live Analytics",
        nav_aff: "Affiliate Network",
        studio_badge: "BROADCAST STUDIO",
        studio_title: "Channel Settings",
        btn_open_studio: "Save Settings",
        channel_owner_label: "Channel under your Creator ID:",
        vip_delivery_title: "VIP Link & Automatic Delivery",
        vip_target_label: "VIP Target (Private Channel / Resource):",
        stars_rate_label: "Rate in Stars (XTR):",
        duration_days_label: "Duration (Days):",
        perimeter_badge: "COMMUNITY PERIMETER",
        groups_title: "Group Control",
        shielded_mode: "Shielded Mode 🟢",
        group_owner_label: "Managed Community:",
        captcha_pro: "Captcha Customs Pro",
        captcha_desc: "Private checkpoint upon entry",
        autolower_title: "Microphone AutoLower (2%)",
        autolower_desc: "Background acoustic attenuation",
        shield_title: "Screen-Sharing Shield",
        shield_desc: "Blocks unauthorized screen share",
        linklock_title: "Web Links Lock",
        linklock_desc: "Instant purge of unapproved URLs",
        watchdog_badge: "MEMBER MONITOR",
        watchdog_title: "Subscription Watchdog",
        live_badge: "Live",
        watchdog_desc: "Real-time tracking of active members and renewal warnings before automated expulsion.",
        profile_balance_stars: "Stars Balance:",
        profile_discount: "Active Discount:",
        profile_rank: "Operational Rank:",
        profile_reg_date: "Registration Date:",
        profile_account_status: "Account Status:",
        btn_terminate_sessions: "Terminate All Active Sessions",
        theme_light: "Light",
        theme_dark: "Dark",
        menu_my_profile: "My profile",
        menu_help: "Help & Support",
        help_support_chat: "Technical support chat",
        help_instruction: "Instruction & Manuals",
        help_test_regex: "Test Regex / Pattern Checker",
        tab_report_error: "Report an error",
        tab_leave_review: "Leave a review",
        click_attach: "Click to attach file",
        btn_cancel: "Cancel",
        btn_send: "Send message",
        instruction_title: "Instructions & Official Manual",
        btn_close: "Close",
        footer_copyright: "The Bunker Command OS © 2026 — Cloud Media Management",
        instruction_body: "The Bunker Command OS manages Telegram communities with industrial-grade automation. Connect your chats, manage permissions in real time, and audit licenses with native Telegram Stars payments.",
        instruction_steps_title: "🚀 Initial steps:",
        instruction_step1: "1. Add the bot as admin in your channel or group.",
        instruction_step2: "2. Sync the ID from the Channel Studio.",
        instruction_step3: "3. Configure your rates in Stars (XTR).",
        regex_title: "Regular Expression Check",
        regex_pattern_label: "Regular expression:",
        regex_string_label: "String to test:",
        regex_lowercase_label: "Cast to lowercase",
        btn_reset: "Reset",
        btn_test: "Test",
        report_placeholder: "Describe the error or review...",
        select_your_channel: "Select your channel...",
        select_your_community: "Select your community...",
        admin_stats_title: "Admin Performance",
        top_users_title: "Top 10 Active Users (30 days)",
        btn_connect_channel: "➕ Connect Channel",
        btn_connect_group: "➕ Connect Group",
        tariff_empty: "Tariff plan empty 🔴",
        tariff_active: "Plan Active 🟢",
        log_channel_label: "Log Channel:",
        status_enabled: "Enabled",
        status_disabled: "Disabled",
        login_title: "Access The Bunker OS",
        login_subtitle: "Authenticate your operator identity to unlock the command panel.",
        login_or: "or",
        login_via_bot: "Login via Bot",
        login_hint: "A secure Telegram window will open to verify your identity. No passwords required.",
        login_verifying: "🔐 Verifying identity...",
        login_error: "⚠️ Could not verify the session. Please try again.",
        login_expired: "⚠️ Your session expired. Please log in again.",
        load_error: "Failed to sync with server",
        btn_retry: "Retry connection",
        action_clone_success: "Clone Bot successfully deployed and active! 🟢",
        action_sentinel_success: "MTProto Sentinel successfully linked! 💎",
        action_purge_started: "Ghost Purge initiated in background 🧹",

        // 📈 Live analytics
        an_badge: "REAL-TIME RADAR",
        an_title: "Community Analytics",
        an_refresh: "Refresh",
        an_toasts_on: "Live alerts on 🔔",
        an_toasts_off: "Live alerts muted 🔕",
        an_empty: "Select a community to see its live analytics.",
        an_loading: "Compiling metrics...",
        an_err_forbidden: "You do not have admin permissions over this community.",
        an_err_unavailable: "Analytics are not available right now.",
        an_updated: "Updated",
        an_kpi_dau: "Active today (DAU)",
        an_kpi_wau: "7 days (WAU)",
        an_kpi_mau: "30 days (MAU)",
        an_kpi_stickiness: "DAU/MAU stickiness",
        an_kpi_messages: "Messages today",
        an_vs_yesterday: "vs. yesterday at this hour",
        an_kpi_members: "Members",
        an_members_tracked: "tracked",
        an_kpi_joins: "Joins 7d / 30d",
        an_kpi_retention: "Cohort retention",
        an_cohort_7d: "7-day cohort",
        an_cohort_30d: "30-day cohort",
        an_kpi_stars: "Stars revenue",
        an_stars_today: "today",
        an_stars_30d: "30 days",
        an_payments: "payments",
        an_spark_messages: "Messages (30 days)",
        an_spark_active: "Active users (30 days)",
        an_spark_growth: "New members (30 days)",
        an_peak_label: "Peak",
        an_heatmap_title: "24/7 Heatmap",
        an_heatmap_empty: "Not enough activity yet",
        an_breakdown_title: "Message Breakdown (30 days)",
        an_leaderboard_title: "Honor Board — Top 10",
        an_level: "Level",
        an_msgs_30d: "msgs/30d",
        an_lb_empty: "Not enough activity for the leaderboard yet",
        an_voice_title: "Voice Room",
        an_voice_idle: "No active call",
        an_voice_live: "Call in progress",
        an_voice_present: "in room",
        an_voice_mics: "open mics",
        an_feed_title: "Live Activity",
        an_feed_empty: "Waiting for live events...",
        kind_text: "text",
        kind_media: "media",
        kind_stickers_gifs: "sticker/GIF",
        kind_commands: "command",
        kind_other: "other",
        ws_live: "Connected 🟢",
        ws_connecting: "Connecting 🟡",
        ws_reconnecting: "Reconnecting 🟡",
        ws_offline: "Offline 🔴",
        ws_paused: "Paused ⚪",
        ws_denied: "No access 🔴",
        ws_idle: "Radar idle",
        toast_level_up_title: "Level up! 🏆",
        toast_level_up_body: "{name} reached level {level}",
        toast_msg_title_one: "New message 💬",
        toast_msg_title_many: "{n} new messages 💬",
        toast_voice_started: "Voice chat started 🎙️",
        toast_voice_ended: "Voice chat ended 🔇",
        toast_payment_title: "Stars payment received ⭐",
        toast_payment_body: "+{stars} Stars from {name}",
        toast_reconnected: "Radar reconnected 🟢",
        feed_message: "{name} · {kind}",
        feed_level_up: "{name} reached level {level}",
        feed_voice_joined: "{names} joined the room",
        feed_voice_left: "{n} left the room",
        feed_payment: "{name} paid {stars} ⭐",

        // 🎬 Channel Studio (reactive saving)
        tariff_plan_label: "Tariff Plan",
        studio_pick_channel: "Select a channel under your Creator ID first.",
        studio_status_dirty: "Unsaved changes…",
        studio_status_saving: "Saving…",
        studio_status_saved: "Saved and verified ✓ {time}",
        studio_status_saved_unverified: "Saved ✓ {time}",
        studio_status_mismatch: "⚠️ Saved, but the server returns different values ({values}). Check the channel plan.",
        studio_status_error: "❌ Could not save: {error}",
        studio_status_invalid: "Check the fields marked in red",
        studio_status_forbidden: "❌ You do not have permissions over this channel",
        studio_err_link: "Use an https:// link, t.me/… or @alias",
        studio_err_link_long: "Maximum {max} characters",
        studio_err_price: "A whole number between {min} and {max} Stars",
        studio_err_days: "A whole number between {min} and {max} days",
        studio_days_unit: "d",

        // 🔐 Telegram session
        session_expired_title: "Session expired",
        session_expired_body: "Your Telegram session is no longer valid. Close and reopen the Mini App from the bot.",
        session_expired_btn: "Close",

        // 🎙️ Sentinel
        sentinel_phone_hint: "Phone sign-in is completed from the bot in private. Paste the String Session here.",

        // 💎 Channel membership plans
        plans_badge: "MEMBERSHIPS",
        plans_title: "Channel Active Plans",
        plans_refresh: "Refresh",
        plans_select_channel: "Select a channel to see its membership plans.",
        plans_loading: "Loading plans...",
        plans_empty: "This channel has no membership plans yet. Create them from the channel panel in the bot (💎 Membership Plans).",
        plans_load_error: "Could not load the plans",
        plans_count: "{active} active · {total} total",
        plans_subscribers: "{n} active subscribers",
        plans_status_active: "Active 🟢",
        plans_status_paused: "Paused 🔴",
        plans_days: "{n} days",
        plans_media_photo: "Photo",
        plans_media_video: "Video",
        plans_media_animation: "GIF",
        plans_btn_preview: "Preview",
        plans_btn_pause: "Pause",
        plans_btn_activate: "Activate",
        plans_btn_broadcast: "Broadcast",
        plans_btn_link: "Link",
        plans_btn_copy: "Copy",
        plans_btn_delete: "Delete",
        plans_tip_preview: "Preview card",
        plans_tip_pause: "Pause plan",
        plans_tip_activate: "Activate plan",
        plans_tip_broadcast: "Broadcast to the channel",
        plans_tip_link: "Generate purchase link",
        plans_tip_copy: "Copy purchase link",
        plans_tip_delete: "Delete plan",
        plans_confirm_delete: "Delete «{name}»? This cannot be undone.",
        plans_confirm_delete_yes: "Yes, delete",
        plans_confirm_broadcast: "Publish «{name}» to the channel now?",
        plans_confirm_broadcast_yes: "Yes, publish",
        plans_confirm_no: "Cancel",
        plans_link_label: "Purchase link with automatic delivery",
        plans_link_hint: "Whoever pays with Stars automatically receives their single-use VIP access link.",
        plans_toast_activated: "Plan activated 🟢",
        plans_toast_paused: "Plan paused 🔴",
        plans_toast_deleted: "Plan deleted 🗑️",
        plans_toast_broadcast: "Announcement published to the channel 📢",
        plans_toast_link_copied: "Purchase link copied 🔗",
        plans_toast_link_ready: "Link generated: tap Copy 🔗",
        plans_toast_link_local: "Link generated locally (your server does not expose this feature)",
        plans_toast_error: "Could not complete: {error}",
        plans_err_missing: "Your server does not expose this feature yet. Update the backend (channel_plans_api).",
        plans_err_forbidden: "You do not have permissions over this channel.",
        plans_err_inactive: "Activate the plan first: a paused plan cannot be purchased or broadcast.",
        plans_toast_copy_failed: "Could not copy: press and hold the link to copy it.",
        plans_preview_title: "Announcement preview",
        plans_preview_hint: "This is how your plan will look in Telegram.",
        plans_preview_duration: "Duration",
        plans_preview_price: "Price",
        plans_preview_subscribe: "⭐ Subscribe ({n} Stars)",
        plans_preview_resource: "🔗 Access VIP Resource",
        plans_preview_media: "Includes: {type}",

        // --- v8.2 · Log Channel modal ---
        logm_badge: "AUDIT",
        logm_title: "Log Channel",
        logm_desc: "Moderation events for this community (bans, captcha, purges) will be posted to this channel.",
        logm_label: "Numeric ID or @alias of the channel",
        logm_placeholder: "-1001234567890 or @MyLogChannel",
        logm_help: "The bot must be an admin of the channel with permission to post, and you must administer it. Leave the field empty and save to disable logging.",
        logm_current: "Current:",
        logm_none: "No log channel",
        logm_community: "Community:",
        logm_save: "Save",
        logm_cancel: "Cancel",
        logm_saving: "Verifying…",
        logm_err_format: "Use a public @alias (5-32 characters) or the channel numeric ID (-100…).",
        logm_toast_saved: "Log channel enabled ✅",
        logm_toast_disabled: "Log channel disabled",
        logm_toast_error: "Could not save the log channel",

        // --- v8.2 · Chat synchronization ---
        sync_toast_title: "Synchronization complete",
        sync_toast_body: "{channels} channels · {groups} communities · {linked} linked now",
        sync_toast_throttled: "You synced a moment ago: showing current data.",
        sync_toast_error: "Synchronization error",

        // --- v8.2 · Studio custom broadcast ---
        bc_section_title: "Automatic Promotion Broadcast",
        bc_ready: "Ultra Ready 🟢",
        bc_status_on: "Scheduled every {h} h 🟢",
        bc_status_off: "Not scheduled ⚪",
        bc_target_label: "Target Chat (@alias or ID):",
        bc_target_placeholder: "@MyCommunity",
        bc_target_hint: "Empty = no automatic broadcast; \"Broadcast Now\" will post to the channel itself.",
        bc_interval_label: "Repeat Interval:",
        bc_interval_6: "Every 6 Hours",
        bc_interval_12: "Every 12 Hours",
        bc_interval_24: "Every 24 Hours (Daily)",
        bc_interval_48: "Every 48 Hours",
        bc_promo_label: "Promotional Message Text / Payload:",
        bc_promo_placeholder: "Access our VIP content with exclusive benefits here! Supports <b>bold</b>, <i>italic</i>, <u>underline</u>, <s>strike</s> and <code>code</code>.",
        bc_btn_preview: "Preview",
        bc_btn_send: "Broadcast Now",
        bc_btn_clear: "Clear",
        bc_err_target: "Use a public @alias (5-32 characters) or the chat numeric ID.",
        bc_err_promo_long: "Maximum {max} characters.",
        bc_err_promo_required: "Write the promotional text to broadcast to the target chat.",
        bc_err_interval: "Pick a valid interval.",
        bc_err_empty: "Write the promotional text first.",
        bc_preview_title: "Broadcast preview",
        bc_preview_hint: "This is how your promotion will be posted on Telegram.",
        bc_preview_target: "Target: {target}",
        bc_preview_target_self: "Target: this channel",
        bc_preview_schedule: "Repeats: every {h} h",
        bc_preview_schedule_off: "Repeats: off (no target chat)",
        bc_preview_buy: "⭐ Get Access (Stars)",
        bc_preview_buy_note: "The purchase button is added when the channel has an active plan.",
        bc_confirm_send: "Publish the promotion to {target} now?",
        bc_confirm_clear: "Clear the broadcast settings? Automatic broadcasting will be turned off.",
        bc_toast_sent: "Promotion published to {target} 📢",
        bc_toast_error: "Could not broadcast: {error}",
        bc_toast_cleared: "Broadcast reset to default values",
        bc_toast_save_first: "Fix the highlighted fields before broadcasting.",

        // --- v8.2 · Group control console ---
        gc_pick_first: "Select a managed community first.",
        gc_switch_on: "ACTIVE 🟢",
        gc_switch_off: "BLOCKED 🔴",
        gc_switch_loading: "Syncing…",
        gc_switch_toast_on: "{name}: enabled",
        gc_switch_toast_off: "{name}: disabled",
        gc_switch_toast_error: "Could not change {name}: {error}",
        gc_ultra_title: "Ultra Tools & MTProto Clones",
        gc_clone_label: "Clone Bot Token (BotFather):",
        gc_btn_deploy: "Deploy",
        gc_sentinel_label: "MTProto Acoustic Sentinel:",
        gc_btn_sentinel: "Connect Sentinel",
        gc_btn_purge: "Run Ghost Purge (Ghost Accounts)",
        gc_running: "Processing…",
        gc_clone_err_token: "Enter the Bot Token generated in @BotFather.",
        gc_clone_err_format: "The token does not match the @BotFather format (123456789:ABC…).",
        gc_clone_toast_ok: "Clone bot @{name} deployed and active 🚀",
        gc_clone_toast_error: "Failed to deploy the clone: {error}",
        gc_sentinel_err_session: "Paste the String Session generated for your MTProto Sentinel.",
        gc_sentinel_toast_ok: "MTProto Sentinel connected 📡",
        gc_sentinel_toast_error: "Failed to connect the sentinel: {error}",
        gc_purge_confirm: "💀 Start purging ghost accounts and deleted profiles in this community?",
        gc_purge_toast_ok: "Ghost Purge running in background ⚡",
        gc_purge_toast_error: "Error starting Ghost Purge: {error}",
        gc_err_generic: "Communication failure",

        // --- v8.3 · Plan generator ---
        pf_title: "VIP Plan Generator",
        pf_desc: "Create a real plan in the channel catalog: it is charged in Telegram Stars and the bot delivers access automatically.",
        pf_name_label: "Plan Name:",
        pf_name_placeholder: "VIP Monthly",
        pf_price_label: "Price in Stars (XTR):",
        pf_days_label: "Duration (Days):",
        pf_link_label: "VIP Destination (optional):",
        pf_link_placeholder: "https://t.me/+... or @alias (extra button after payment)",
        pf_promo_label: "Promotional Text / Payload:",
        pf_promo_placeholder: "Describe the benefit. Supports <b>bold</b>, <i>italic</i>, <u>underline</u>, <s>strike</s> and <code>code</code>.",
        pf_btn_create: "Create & Activate",
        pf_btn_preview: "Preview",
        pf_btn_broadcast: "Broadcast",
        pf_btn_clear: "Clear",
        pf_creating: "Creating…",
        pf_err_name: "Between 1 and {max} characters.",
        pf_err_price: "A whole number between {min} and {max} Stars.",
        pf_err_days: "A whole number between {min} and {max} days.",
        pf_err_link: "Use an https:// link, t.me/+… or an @alias.",
        pf_err_promo: "Maximum {max} characters.",
        pf_toast_created: "Plan “{name}” created and active 💎",
        pf_toast_created_body: "Delivery verified: the bot can invite buyers.",
        pf_toast_created_warn: "Plan created, but the bot CANNOT invite in the channel: make it an admin with the invite permission.",
        pf_toast_error: "Could not create the plan: {error}",
        pf_toast_invalid: "Check the highlighted plan fields.",
        pf_toast_cleared: "Plan form cleared",
        pf_confirm_broadcast_new: "The plan “{name}” will be created, activated and published to the channel. Continue?",
        pf_confirm_broadcast: "Publish the plan “{name}” to the channel now?",
        pf_check_link: "Verification link (1 use · 24 h)",

        // --- v8.3 · Programming console ---
        cfg_title: "Bot Programming",
        cfg_desc: "Every change governs the bot's behavior in the community instantly.",
        cfg_loading: "Loading configuration…",
        cfg_pick: "Select a community to program the bot.",
        cfg_save: "Save",
        cfg_saving: "Saving…",
        cfg_status_saved: "Saved ✓ {time}",
        cfg_status_dirty: "Unsaved changes",
        cfg_status_invalid: "Check the highlighted fields",
        cfg_status_error: "Error: {error}",
        cfg_status_remote: "Updated from another device",
        cfg_toast_saved: "{section}: configuration saved ✅",
        cfg_toast_error: "{section}: could not save — {error}",
        cfg_toast_switch_on: "{name}: enabled",
        cfg_toast_switch_off: "{name}: disabled",
        cfg_switch_on: "ON",
        cfg_switch_off: "OFF",
        cfg_sec_aduana: "Customs & Welcome",
        cfg_sec_aduana_desc: "Verification challenge for new members and welcome message.",
        cfg_sec_acoustic: "Acoustics & Video Chat",
        cfg_sec_acoustic_desc: "Automatic ducking, screen shield and video chat prices.",
        cfg_sec_tips: "Tips & Monetization",
        cfg_sec_tips_desc: "Voluntary contributions in Telegram Stars for the community.",
        cfg_sec_perimeter: "Perimeter & Filters",
        cfg_sec_perimeter_desc: "Links, message flooding and service notice cleanup.",
        cfg_captcha_enabled: "Captcha Customs Pro",
        cfg_captcha_mode: "Challenge Mode:",
        cfg_captcha_mode_button: "Simple button (“I am human”)",
        cfg_captcha_mode_math: "Arithmetic challenge",
        cfg_captcha_timeout: "Time Limit:",
        cfg_seconds: "{n} s",
        cfg_custom_welcome: "Welcome Message:",
        cfg_welcome_placeholder: "Welcome {name} to {title}! Read the pinned rules.",
        cfg_welcome_vars: "Variables:",
        cfg_autolower_enabled: "Microphone AutoLower",
        cfg_autolower_pct: "Ducking:",
        cfg_shield_enabled: "Screen-Sharing Shield",
        cfg_micvip_price: "VIP Pass 24h (MicVIP) ⭐:",
        cfg_speaker_price: "Priority Turn (AMA Queue) ⭐:",
        cfg_tips_enabled: "Tips in Stars",
        cfg_tips_presets: "Quick amounts (comma separated):",
        cfg_tips_presets_placeholder: "15, 50, 100, 250, 500",
        cfg_custom_tips_allowed: "Allow custom amount",
        cfg_linklock_enabled: "Link Lock (LinkLock)",
        cfg_antiflood_enabled: "Anti-Flood",
        cfg_antiflood_rate: "Messages allowed:",
        cfg_antiflood_window: "per window (s):",
        cfg_service_cleaner_enabled: "Purge service messages (joins/leaves)",
        cfg_err_bool: "Invalid value.",
        cfg_err_range: "Between {min} and {max}.",
        cfg_err_presets: "Between 1 and {max} whole amounts from 1 to 10000.",
        cfg_err_welcome_long: "Maximum {max} characters.",
        cfg_err_welcome_var: "Unknown variable {{var}}. Use {name}, {username} or {title}.",
        cfg_actions_title: "Tactical Tools"
    }
};